import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";


import { Toaster } from "@/components/ui/toaster"




const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Routes App",
  description: "Generated by create next app",
  icons: {
    icon: '/wawa.png', // Ruta relativa a la imagen en la carpeta public
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <script
        src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
        async
        defer
      ></script>

      <link rel="icon" href="/app/wawa.png" sizes="any" />

      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}
      >
        <main className="container mx-auto pt-5" >{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
